blueprint:
  name: Toggleable Motion Light
  description: Turn on a light when motion is detected, if the specified switch is on
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
    light:
      name: Light
      selector:
        entity:
          domain: light
    switch_entity:
      name: Motion Switch
      selector:
        entity:
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 5
      selector:
        number:
          min: 0
          max: 1440
          unit_of_measurement: minutes
    extra_on_actions:
      name: Extra On Actions
      description: Additional actions to run when motion is detected
      selector:
        action:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    to: "on"
  - platform: state
    entity_id: !input motion_entity
    to: "off"
    id: no_motion
    for:
      minutes: !input no_motion_wait
  - platform: state
    entity_id: !input light
    to: "on"
    id: lights_on
  - platform: state
    entity_id: !input switch_entity
    to: "on"
    id: motion_turn_on

condition:
  - condition: state
    entity_id: !input switch_entity
    state: 'on'

action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - no_motion
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light
      - conditions:
          - condition: trigger
            id:
              - lights_on
              - motion_turn_on
        sequence:
          - delay:
              minutes: !input no_motion_wait
          - condition: state
            entity_id: !input switch_entity
            state: "on"
          - service: light.turn_off
            target:
              entity_id: !input light
    default:
      - service: light.turn_on
        target:
          entity_id: !input light
      # probably not necessary but unsure how to append
      # the input actions to the above list
      if:
        - condition: template
          value_template: "{{ True }}"
      then: !input extra_on_actions
