blueprint:
  name: Toggleable Motion Light
  description: Turn on a light when motion is detected, if the specified switch is on. Also calls turn_off twice, I have issues with some groups not completely turning off the first time.
  domain: automation
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    switch_entity:
      name: Motion Switch
      selector:
        entity:
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"
    
condition:
  - condition: state
    entity_id: !input switch_entity
    state: 'on'

action:
  - service: light.turn_on
    target: !input light_target
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - condition: state
    entity_id: !input switch_entity
    state: 'on'
  - service: light.turn_off
    target: !input light_target
  - delay: 3
  - service: light.turn_off
    target: !input light_target
